# Generated by Django 5.0.6 on 2024-06-15 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0007_customuser_address_customuser_city_customuser_mobile_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
